name: Deploy

on:
  push:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [14.x]

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - run: npm ci
    - run: npm test
    - run: npm run build
    - name: 'List built files'
      run: ls -R dist/
    - name: 'Compress build artifact'
      run: zip -r build.zip dist/ views/ data/ package.json package-lock.json
    - name: Upload transpiled source
      uses: actions/upload-artifact@v1
      with:
        name: build
        path: build.zip
