name: Deploy

on:
  push:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [14.x]

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - run: npm ci
    - run: npm test
    - run: npm run build
    - name: List built files
      run: ls -R dist/
    - name: Build docker image
      id: build-image
      env:
        PROJECT_ID: crit-role
        IMAGE_TAG: ${{ github.sha }}
      run: docker build -t gcr.io/$PROJECT_ID/test:$IMAGE_TAG .
